# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- gradle-calculator

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  displayName: validate
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: 'validate'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
